# Generated by Django 5.0.1 on 2024-01-07 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="deadline_datetime",
        ),
        migrations.AddField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 1, 6, 15, 49, 9, 878723)
            ),
        ),
    ]
