# Generated by Django 5.0.1 on 2024-01-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_remove_task_deadline_datetime_task_deadline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_done", "-created_datetime"]},
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(null=True),
        ),
    ]
